[1주차] 스터디에 임하는 각오
dsc-sookmyung/2022-02-Spring-Novice-Study pull request #14
Opened 2022-09-28 09:27 UTC by yunjaeeun44

잘 부탁드립니다!

2022-10-01 17:45 UTC, yejin9858 requested changes
'스터디에'라는 파일이 잘못 추가된 것 같아요! 확인해보시고 수정 부탁드려요!!

2022-10-02 08:02 UTC, yunjaeeun44 commented
@yejin9858  삭제 했는데 잘 된 건지 확인부탁드려도 될까요??

2022-10-02 08:58 UTC, yejin9858 approved these changes

2022-10-02 08:58 UTC, merged

2022-10-02 08:59 UTC, yejin9858 commented
확인했습니다 고생하셨습니다!