[김한비] 2022 GDSC Spring Study 입문 - 3주차
dsc-sookmyung/2022-02-Spring-Novice-Study pull request #58
Opened 2022-10-29 03:26 UTC by ddubii

### 🤩 이번 주에 배운 내용 간단 요약

mustache와 postman으로 화면 구성하고 게시글 수정,삭제,조회 기능 확인하기

### 📎 배운 내용을 정리한 링크
(https://www.notion.so/3-426740d2db8841969cdd6d23a0accae2)
-정리는 아직 하는 중이에요 추가하겠습니다!... 추가 실습 캡쳐만 확인해주세요

### 🤔 나중에 더 공부해보고 싶은 내용

### 🐹 더 하고싶은 말

2022-10-31 02:51 UTC, Mingadinga commented
한비님 노션 링크 접근 권한이 없다고 뜨네요..! 외부 접근 허용해주시겠어요?😃

2022-11-02 10:00 UTC, yejin9858 requested changes
고생하셨습니다 :) 위에 휘님 말대로 노션 접근권한 확인 부탁드려요!

2022-11-06 11:54 UTC, ddubii commented
아이고 이제 확인했네요..! 
https://ember-slope-7c6.notion.site/3-426740d2db8841969cdd6d23a0accae2
접근 허용 했습니다!

2022-11-06 12:02 UTC, merged

2022-11-06 12:02 UTC, yejin9858 reviewed
확인했습니다