[류현지] 2022 GDSC Spring Study 입문 - 3주차
dsc-sookmyung/2022-02-Spring-Novice-Study pull request #62
Opened 2022-10-30 05:36 UTC by Ryuuhj

### 🤩 이번 주에 배운 내용 간단 요약
- @Controller Vs. @RestController 차이
- 템플릿 엔진, 그 중 하나인 머스테치 사용해보기
- 게시판 시작화면, 게시글 등록/확인/수정/삭제 기능 추가 및 테스트
- Postman 프로그램을 통한 (뷰 없이) 컨트롤러 동작 테스트 

### 📎 배운 내용을 정리한 링크
https://defiant-coat-2e2.notion.site/Chap4-c1af28b13dd744b2b52e8b6404ef162b

### 🤔 나중에 더 공부해보고 싶은 내용
클라이언트 템플릿 엔진에 대해 더 공부해보고 싶습니다.

### 🐹 더 하고싶은 말

2022-11-02 10:14 UTC, yejin9858 approved these changes
고생하셨습니다 :)
추가적으로, IndexController는 dto가 아니므로, dto 폴더에서 빼는 것이 프로젝트 구조 상 좋습니다!

2022-11-02 10:23 UTC, yejin9858 requested changes
혹시 [추가실습](https://www.notion.so/3-b267f4c713a6483686b79f3fe0d672da) 관련 내용이 안보이는데 빠뜨리신 걸까요? 제가 못 본 것이라면 DM 주시고, 그렇지 않다면 추가실습도 같이 부탁드립니다~

2022-11-05 22:36 UTC, yejin9858 approved these changes
원래 있었던 것인지 추가해주신 것인지는 잘 모르겠지만... 실습 캡쳐 찾았습니다! 고생하셨어요:)

2022-11-05 22:36 UTC, merged

2022-11-06 13:15 UTC, Ryuuhj commented
앗 이제서야 확인했어요 죄송합니다.. 따로 수정한건 아니고 요약 페이지에서 하위 페이지로 첨부하고 따로 말씀을 안 드렸어요!! IndexController도 수정하겠습니다! 알려주셔서 감사해요ㅎㅎ