[임아현] 2021 GDSC Spring Study 입문 - 3주차
dsc-sookmyung/2022-02-Spring-Novice-Study pull request #74
Opened 2022-11-03 14:52 UTC by ahyeon-github

### 🤩 이번 주에 배운 내용 간단 요약

머스테치로 화면 구성하기
등록/조회/수정/삭제 화면 만들기
postman을 활용한 실습

### 📎 배운 내용을 정리한 링크

### 🤔 나중에 더 공부해보고 싶은 내용

### 🐹 더 하고싶은 말

2022-11-05 22:50 UTC, yejin9858 approved these changes

2022-11-05 22:51 UTC, yejin9858 requested changes
포스트맨 실습 사진도 첨부 부탁드려요~!

2022-11-13 08:41 UTC, ahyeon-github commented
<img width="1512" alt="스크린샷 2022-11-13 오후 5 10 17" src="https://user-images.githubusercontent.com/80513699/201512250-819b1fae-8914-4f5a-b99c-7f06febaa7b7.png">


<img width="1512" alt="스크린샷 2022-11-13 오후 5 36 29" src="https://user-images.githubusercontent.com/80513699/201513096-2e97e0e1-73f0-417b-9fea-f41803a913ac.png">
 

<img width="1512" alt="스크린샷 2022-11-13 오후 5 40 57" src="https://user-images.githubusercontent.com/80513699/201513267-dd847d86-f965-4f33-9b64-382f2eee6acb.png">


<img width="1512" alt="스크린샷 2022-11-13 오후 5 41 12" src="https://user-images.githubusercontent.com/80513699/201513279-f5cdcdca-9479-43ca-9998-aa7d62254411.png">




<img width="1512" alt="스크린샷 2022-11-13 오후 5 41 58" src="https://user-images.githubusercontent.com/80513699/201513309-60ee3279-5132-4dc3-aff1-3aa3527da784.png">



<img width="1512" alt="스크린샷 2022-11-13 오후 5 42 15" src="https://user-images.githubusercontent.com/80513699/201513319-2a254918-ea27-4c38-9024-e9288c162c1f.png">

2022-11-13 08:41 UTC, ahyeon-github commented
@yejin9858 실습 화면 첨부합니다!

2022-11-13 11:05 UTC, yejin9858 approved these changes
고생하셨습니다

2022-11-13 11:05 UTC, merged